import type { ConnectionCommandMap } from "@/runtime/ipc/contracts/connection";
import type { DeviceCommandMap } from "@/runtime/ipc/contracts/device";
import type { IpcCommand } from "@/runtime/ipc/contracts/common";
import type { MirrorCommandMap } from "@/runtime/ipc/contracts/mirror";
import type { MockCommandMap } from "@/runtime/ipc/contracts/mock";
import type { RecordingCommandMap } from "@/runtime/ipc/contracts/recording";
import type { SessionCommandMap } from "@/runtime/ipc/contracts/session";
import type { StorageCommandMap } from "@/runtime/ipc/contracts/storage";

export interface IpcCommandMap
  extends
    SessionCommandMap,
    DeviceCommandMap,
    ConnectionCommandMap,
    MirrorCommandMap,
    StorageCommandMap,
    RecordingCommandMap,
    MockCommandMap {}

export type IpcCommandName = keyof IpcCommandMap;
export type IpcCommandArgs<Name extends IpcCommandName> = IpcCommandMap[Name]["args"];
export type IpcCommandResult<Name extends IpcCommandName> = IpcCommandMap[Name]["result"];

export type IpcNoArgsCommand = {
  [Name in IpcCommandName]: IpcCommandArgs<Name> extends undefined ? Name : never;
}[IpcCommandName];

export type IpcArgsCommand = Exclude<IpcCommandName, IpcNoArgsCommand>;
export type IpcCommandDefinition = IpcCommand<object | undefined, unknown>;

export const IPC_COMMAND_NAMES = [
  "session_list_devices",
  "session_get_registry_state",
  "session_refresh_devices",
  "session_set_active_device",
  "session_get_device_info",
  "session_shell_command",
  "session_tcpip",
  "session_reboot",
  "session_root",
  "session_list_packages",
  "session_refresh_packages",
  "session_cancel_list_packages",
  "session_open_package",
  "session_reverse",
  "session_remove_reverse",
  "session_list_reverse",
  "session_list_webview_sockets",
  "session_list_targets",
  "session_refresh_targets",
  "session_start_logcat_lease",
  "session_stop_logcat_lease",
  "session_start_perf_lease",
  "session_stop_perf_lease",
  "session_start_mirror_lease",
  "session_stop_mirror_lease",
  "session_attach_console_target",
  "session_detach_console_target",
  "adb_start_server",
  "adb_list_devices",
  "adb_get_device_info",
  "adb_shell_command",
  "adb_connect_device",
  "adb_disconnect_device",
  "adb_pair_device",
  "adb_tcpip",
  "adb_reboot",
  "adb_root",
  "adb_restart_server",
  "adb_list_packages",
  "adb_cancel_list_packages",
  "adb_get_package_details",
  "adb_open_package",
  "adb_get_app_icon",
  "adb_list_webview_sockets",
  "adb_reverse",
  "adb_remove_reverse",
  "adb_list_reverse",
  "start_logcat",
  "stop_logcat",
  "adb_forward_cdp",
  "adb_remove_forward",
  "adb_fetch_json_targets",
  "cdp_start_proxy",
  "cdp_stop_proxy",
  "chrome_find",
  "chrome_is_running",
  "chrome_kill_all",
  "chrome_launch",
  "chrome_verify_port",
  "chrome_fetch_targets",
  "chrome_open_devtools_url",
  "chrome_open_target",
  "chrome_activate_target",
  "adb_mirror_scrcpy_start",
  "adb_mirror_scrcpy_stop",
  "adb_mirror_launch_scrcpy",
  "adb_mirror_stop_scrcpy",
  "adb_mirror_screenshot",
  "adb_mirror_get_screen_size",
  "adb_mirror_keyevent",
  "adb_mirror_inject_keycode",
  "adb_mirror_inject_text",
  "adb_mirror_scroll_event",
  "adb_mirror_set_clipboard",
  "adb_mirror_get_clipboard",
  "adb_mirror_touch_event",
  "adb_mirror_tap",
  "adb_mirror_swipe",
  "adb_mirror_start_recording",
  "adb_mirror_stop_recording",
  "adb_perf_start",
  "adb_perf_stop",
  "adb_list_dir",
  "adb_pull_file",
  "adb_read_file",
  "adb_open_file",
  "adb_open_file_picker",
  "adb_delete_file",
  "show_in_folder",
  "save_base64_file",
  "read_local_file_base64",
  "sqlite_list_databases",
  "sqlite_scan_all_databases",
  "sqlite_open_database",
  "sqlite_refresh_database",
  "sqlite_close_database",
  "sqlite_save_local_bytes",
  "sqlite_overwrite_local_bytes",
  "sqlite_table_columns",
  "sqlite_table_indexes",
  "sqlite_table_foreign_keys",
  "sqlite_table_rows",
  "sqlite_execute_query",
  "sqlite_execute_write",
  "sqlite_export_bytes",
  "mock_server_start",
  "mock_server_stop",
  "mock_server_sync_rules",
  "mock_server_status",
  "recording_session_start",
  "recording_session_append",
  "recording_session_stop",
  "recording_list_sessions",
  "recording_delete_session",
  "recording_read_session",
  "recording_cleanup_orphans",
  "recording_database_snapshot_begin",
  "recording_database_snapshot_page",
  "recording_database_snapshot_finish",
  "recording_database_sources",
  "recording_database_table_rows",
  "recording_database_changed_rows",
  "recording_database_change_summaries",
  "recording_database_change_summary",
  "recording_database_changes_for_keys",
  "local_device_name",
  "local_webview_open_devtools",
  "local_webview_fetch_cdp_target",
  "local_webview_inject_scrollbar_hide",
  "local_webview_navigate",
] as const satisfies readonly IpcCommandName[];

type MissingCommand = Exclude<IpcCommandName, (typeof IPC_COMMAND_NAMES)[number]>;
export const IPC_COMMAND_CONTRACT_COMPLETE: MissingCommand extends never ? true : never = true;
